# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d5202b0671b071295f8ae33d7d5ab4579c8973477425110c678383549be5abfcd7348173baff2cc96bac8ca51012e5f8f936daff4f71c3868c8fd49cfb8692

test:
  secret_key_base: 7eda632dc445d9496dd7f605b3dd3105a0695c7cf528d94f2a504f2c6fee7ec9db2f253e4dd524f9bd7ef04cf1ce1df709ceefb5ed1569598f9856e11b7d0bb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
